// Generated by CoffeeScript 1.3.3
(function() {

  App.RegisterCommand = (function() {

    function RegisterCommand() {
      'Register command';

    }

    return RegisterCommand;

  })();

}).call(this);
